"""Known INS codes we can promote without an LLM.

Risk matches the existing additives.json scale: low / medium / high.
Parser ghosts never belong here — they are rejected by additive_growth.
"""

# code -> {name, category, risk}
CODEX = {
    "ins101": {"name": "Riboflavin", "category": "colour", "risk": "low"},
    "ins120": {"name": "Carmine", "category": "colour", "risk": "medium"},
    "ins127": {"name": "Erythrosine", "category": "artificial_colour", "risk": "high"},
    "ins132": {"name": "Indigotine", "category": "artificial_colour", "risk": "medium"},
    "ins140": {"name": "Chlorophylls", "category": "colour", "risk": "low"},
    "ins141": {"name": "Copper Chlorophylls", "category": "colour", "risk": "medium"},
    "ins142": {"name": "Green S", "category": "artificial_colour", "risk": "high"},
    "ins143": {"name": "Fast Green FCF", "category": "artificial_colour", "risk": "medium"},
    "ins145": {"name": "Brown FK", "category": "artificial_colour", "risk": "high"},
    "ins150": {"name": "Caramel Colour", "category": "colour", "risk": "medium"},
    "ins150a": {"name": "Plain Caramel", "category": "colour", "risk": "low"},
    "ins155": {"name": "Brown HT", "category": "artificial_colour", "risk": "high"},
    "ins160": {"name": "Carotenoids", "category": "colour", "risk": "low"},
    "ins160a": {"name": "Beta-Carotene", "category": "colour", "risk": "low"},
    "ins160b": {"name": "Annatto", "category": "colour", "risk": "medium"},
    "ins160e": {"name": "Beta-Apo-8'-Carotenal", "category": "colour", "risk": "medium"},
    "ins162": {"name": "Beet Red", "category": "colour", "risk": "low"},
    "ins212": {"name": "Potassium Benzoate", "category": "preservative", "risk": "medium"},
    "ins221": {"name": "Sodium Sulphite", "category": "preservative", "risk": "high"},
    "ins222": {"name": "Sodium Hydrogen Sulphite", "category": "preservative", "risk": "high"},
    "ins233": {"name": "Thiabendazole", "category": "preservative", "risk": "high"},
    "ins235": {"name": "Natamycin", "category": "preservative", "risk": "medium"},
    "ins261": {"name": "Potassium Acetate", "category": "acidity_regulator", "risk": "low"},
    "ins262": {"name": "Sodium Acetate", "category": "acidity_regulator", "risk": "low"},
    "ins269": {"name": "Acetic Acid", "category": "acidity_regulator", "risk": "low"},
    "ins281": {"name": "Sodium Propionate", "category": "preservative", "risk": "low"},
    "ins297": {"name": "Fumaric Acid", "category": "acidity_regulator", "risk": "low"},
    "ins301": {"name": "Sodium Ascorbate", "category": "antioxidant", "risk": "low"},
    "ins302": {"name": "Calcium Ascorbate", "category": "antioxidant", "risk": "low"},
    "ins304": {"name": "Ascorbyl Palmitate", "category": "antioxidant", "risk": "low"},
    "ins306": {"name": "Tocopherol Concentrate", "category": "antioxidant", "risk": "low"},
    "ins307a": {"name": "Alpha-Tocopherol", "category": "antioxidant", "risk": "low"},
    "ins307b": {"name": "Tocopherol-Rich Extract", "category": "antioxidant", "risk": "low"},
    "ins307c": {"name": "Delta-Tocopherol", "category": "antioxidant", "risk": "low"},
    "ins309": {"name": "Delta-Tocopherol", "category": "antioxidant", "risk": "low"},
    "ins310": {"name": "Propyl Gallate", "category": "antioxidant", "risk": "high"},
    "ins311": {"name": "Octyl Gallate", "category": "antioxidant", "risk": "high"},
    "ins316": {"name": "Sodium Erythorbate", "category": "antioxidant", "risk": "low"},
    "ins325": {"name": "Sodium Lactate", "category": "acidity_regulator", "risk": "low"},
    "ins332": {"name": "Potassium Citrates", "category": "acidity_regulator", "risk": "low"},
    "ins340": {"name": "Potassium Phosphates", "category": "acidity_regulator", "risk": "medium"},
    "ins341": {"name": "Calcium Phosphates", "category": "acidity_regulator", "risk": "medium"},
    "ins350": {"name": "Sodium Malates", "category": "acidity_regulator", "risk": "low"},
    "ins355": {"name": "Adipic Acid", "category": "acidity_regulator", "risk": "low"},
    "ins365": {"name": "Sodium Fumarate", "category": "acidity_regulator", "risk": "low"},
    "ins385": {"name": "Calcium Disodium EDTA", "category": "antioxidant", "risk": "medium"},
    "ins386": {"name": "Disodium EDTA", "category": "antioxidant", "risk": "medium"},
    "ins392": {"name": "Rosemary Extract", "category": "antioxidant", "risk": "low"},
    "ins401": {"name": "Sodium Alginate", "category": "thickener", "risk": "low"},
    "ins406": {"name": "Agar", "category": "thickener", "risk": "low"},
    "ins411": {"name": "Oat Gum", "category": "thickener", "risk": "low"},
    "ins416": {"name": "Karaya Gum", "category": "thickener", "risk": "low"},
    "ins418": {"name": "Gellan Gum", "category": "thickener", "risk": "low"},
    "ins420": {"name": "Sorbitol", "category": "sweetener", "risk": "medium"},
    "ins433": {"name": "Polysorbate 80", "category": "emulsifier", "risk": "medium"},
    "ins435": {"name": "Polysorbate 60", "category": "emulsifier", "risk": "medium"},
    "ins442": {"name": "Ammonium Phosphatides", "category": "emulsifier", "risk": "medium"},
    "ins444": {"name": "Sucrose Acetate Isobutyrate", "category": "emulsifier", "risk": "medium"},
    "ins452": {"name": "Polyphosphates", "category": "stabilizer", "risk": "medium"},
    "ins459": {"name": "Beta-Cyclodextrin", "category": "stabilizer", "risk": "medium"},
    "ins460": {"name": "Cellulose", "category": "anti_caking", "risk": "low"},
    "ins461": {"name": "Methyl Cellulose", "category": "thickener", "risk": "medium"},
    "ins464": {"name": "Hydroxypropyl Methyl Cellulose", "category": "thickener", "risk": "medium"},
    "ins468": {"name": "Cross-linked Sodium CMC", "category": "stabilizer", "risk": "medium"},
    "ins469": {"name": "Enzymatically Hydrolysed CMC", "category": "stabilizer", "risk": "medium"},
    "ins470": {"name": "Salts of Fatty Acids", "category": "emulsifier", "risk": "medium"},
    "ins470a": {"name": "Sodium/Potassium/Calcium Salts of Fatty Acids", "category": "emulsifier", "risk": "medium"},
    "ins470b": {"name": "Magnesium Salts of Fatty Acids", "category": "emulsifier", "risk": "medium"},
    "ins472a": {"name": "Acetic Acid Esters of Mono- and Diglycerides", "category": "emulsifier", "risk": "medium"},
    "ins472b": {"name": "Lactic Acid Esters of Mono- and Diglycerides", "category": "emulsifier", "risk": "medium"},
    "ins472c": {"name": "Citric Acid Esters of Mono- and Diglycerides", "category": "emulsifier", "risk": "medium"},
    "ins472e": {"name": "DATEM", "category": "emulsifier", "risk": "medium"},
    "ins475": {"name": "Polyglycerol Esters of Fatty Acids", "category": "emulsifier", "risk": "medium"},
    "ins477": {"name": "Propylene Glycol Esters of Fatty Acids", "category": "emulsifier", "risk": "medium"},
    "ins481": {"name": "Sodium Stearoyl Lactylate", "category": "emulsifier", "risk": "medium"},
    "ins491": {"name": "Sorbitan Monostearate", "category": "emulsifier", "risk": "medium"},
    "ins492": {"name": "Sorbitan Tristearate", "category": "emulsifier", "risk": "medium"},
    "ins504": {"name": "Magnesium Carbonate", "category": "anti_caking", "risk": "low"},
    "ins509": {"name": "Calcium Chloride", "category": "firming_agent", "risk": "low"},
    "ins510": {"name": "Ammonium Chloride", "category": "flavour_enhancer", "risk": "medium"},
    "ins514": {"name": "Sodium Sulphate", "category": "acidity_regulator", "risk": "low"},
    "ins516": {"name": "Calcium Sulphate", "category": "firming_agent", "risk": "low"},
    "ins521": {"name": "Aluminium Sulphate", "category": "firming_agent", "risk": "medium"},
    "ins524": {"name": "Sodium Hydroxide", "category": "acidity_regulator", "risk": "medium"},
    "ins525": {"name": "Potassium Hydroxide", "category": "acidity_regulator", "risk": "medium"},
    "ins529": {"name": "Calcium Oxide", "category": "acidity_regulator", "risk": "medium"},
    "ins535": {"name": "Sodium Ferrocyanide", "category": "anti_caking", "risk": "medium"},
    "ins536": {"name": "Potassium Ferrocyanide", "category": "anti_caking", "risk": "medium"},
    "ins541": {"name": "Sodium Aluminium Phosphate", "category": "raising_agent", "risk": "medium"},
    "ins550": {"name": "Sodium Silicate", "category": "anti_caking", "risk": "medium"},
    "ins550i": {"name": "Sodium Silicate", "category": "anti_caking", "risk": "medium"},
    "ins559": {"name": "Aluminium Silicate", "category": "anti_caking", "risk": "medium"},
    "ins575": {"name": "Glucono-Delta-Lactone", "category": "acidity_regulator", "risk": "low"},
    "ins579": {"name": "Ferrous Gluconate", "category": "colour_retention", "risk": "low"},
    "ins632": {"name": "Dipotassium Inosinate", "category": "flavour_enhancer", "risk": "high"},
    "ins900": {"name": "Dimethylpolysiloxane", "category": "antifoaming_agent", "risk": "medium"},
    "ins901": {"name": "Beeswax", "category": "glazing_agent", "risk": "low"},
    "ins903": {"name": "Carnauba Wax", "category": "glazing_agent", "risk": "low"},
    "ins904": {"name": "Shellac", "category": "glazing_agent", "risk": "low"},
    "ins924a": {"name": "Potassium Bromate", "category": "flour_treatment", "risk": "high"},
    "ins953": {"name": "Isomalt", "category": "sweetener", "risk": "medium"},
    "ins961": {"name": "Neotame", "category": "sweetener", "risk": "medium"},
    "ins965": {"name": "Maltitol", "category": "sweetener", "risk": "medium"},
    "ins968": {"name": "Erythritol", "category": "sweetener", "risk": "low"},
    "ins1100": {"name": "Amylase", "category": "enzyme", "risk": "low"},
    "ins1102": {"name": "Glucose Oxidase", "category": "enzyme", "risk": "low"},
    "ins1104": {"name": "Lipase", "category": "enzyme", "risk": "low"},
    "ins1200": {"name": "Polydextrose", "category": "bulking_agent", "risk": "low"},
    "ins1400": {"name": "Dextrin", "category": "modified_starch", "risk": "low"},
    "ins1401": {"name": "Acid-Treated Starch", "category": "modified_starch", "risk": "low"},
    "ins1404": {"name": "Oxidized Starch", "category": "modified_starch", "risk": "low"},
    "ins1405": {"name": "Enzyme-Treated Starch", "category": "modified_starch", "risk": "low"},
    "ins1412": {"name": "Distarch Phosphate", "category": "modified_starch", "risk": "low"},
    "ins1420": {"name": "Acetylated Starch", "category": "modified_starch", "risk": "low"},
    "ins1422": {"name": "Acetylated Distarch Adipate", "category": "modified_starch", "risk": "low"},
    "ins1440": {"name": "Hydroxypropyl Starch", "category": "modified_starch", "risk": "low"},
    "ins1450": {"name": "Starch Sodium Octenyl Succinate", "category": "modified_starch", "risk": "low"},
    "ins1451": {"name": "Acetylated Oxidized Starch", "category": "modified_starch", "risk": "low"},
    "ins1520": {"name": "Propylene Glycol", "category": "humectant", "risk": "medium"},
}
